# Site Settings
baseurl: ""
url: "https://hyunseochoi.github.io"

# Blog Settings
theme_settings:
  title: HyunSeo's Devlog
  favicon: assets/favicon.ico

  # Profile Settings
  profile:
    image: assets/img/smile.png
    username: HYUNSEO CHOI
    description: 세계 정복까지는 아니더라도 세계 여행 정도는 하고 싶은 개발자
    experience:
      - start: 2019-01-07
        end: 2019-01-18
        experience: Internship, ICT Company
      - start: 2019-04-29
        end: 2019-12-19
        experience: 10th Trainee, SW Maestro
      - start: 2019-10-17
        end: 2020-05-15
        experience: Book Translator, Acorn Pub
    skills:
      - skill: Node.js & React
        value: 85
      - skill: C# & Unity
        value: 45

  # Icons
  icons:
    email: dev.hyunseo@gmail.com
    linkedin: # Full URL
    github: HyunSeoChoi
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname:

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
