# Site Settings
baseurl: ""
url : "https://hyunseochoi.github.io"

# Blog Settings
theme_settings :
  title : HyunSeo's Devlog
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Hyunseo Choi
    description : A developer who dreams of becoming the strongest in the universe! I'm also dreaming of conquering the world.
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : Node.js & React
        value : 85  # Percent value
        
  # Icons
  icons :
    email: dev.hyunseo@gmail.com
    linkedin:  # Full URL 
    github: HyunSeoChoi
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
